---

- name: barnyard2 | configuring barnyard2
  template:
    src: "etc/barnyard2/barnyard2.conf.j2"
    dest: "/etc/barnyard2/barnyard2.conf"
    owner: root
    group: root
    mode: 0644

- name: barnyard2 | starting and enabling barnyard2 service
  service:
    name: "barnyard2"
    state: started
    enabled: yes
