---

# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: downloading snort commmunity rules
  get_url:
    url: "{{ snort_community_rules_url }}/{{ snort_community_rules_package }}"
    dest: "/tmp/{{ snort_community_rules_package }}"

- name: extracting snort commmunity rules
  unarchive:
    src: "/tmp/{{ snort_community_rules_package }}"
    dest: "{{ snort_rule_path }}"
    copy: no

- name: Ensure snort is started and enabled to start at boot.
  service:
    name: snort
    state: started
    enabled: yes

- include: barnyard2.yml
  when: snort_barnyard2_enable
